// src\CamBridge.Config\Views\ServiceControlPage.xaml.cs
// Version: 0.5.26
// Ultra-minimal - relies on XAML generated code

namespace CamBridge.Config.Views
{
    public partial class ServiceControlPage
    {
        // Constructor is generated by XAML
        // Page_Unloaded is generated by XAML

        // TODO: Add ViewModel initialization later
    }
}
